import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const geist = localFont({
  src: "../public/fonts/Geist.ttf",
  variable: "--font-geist",
  display: "swap",
});

const sen = localFont({
  src: "../public/fonts/Sen.ttf",
  variable: "--font-sen",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${sen.variable}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
